### ISSUE TITLE
Is it possible send data via a proxy server to kinesis.

### ISSUE THREAD

**Issue by jaskarangump** [samcday/logstash-output-kinesis#23]
We have egress rules configured in the server to only send data via the proxy server, which has whitelisting. Is it possible to configure that?

**Comment by samcday** [comment]
I don't believe so. I had mostly the same use case as you a while ago, which is why I raised awslabs/amazon-kinesis-producer#13 a couple of years ago :) According to the update there from the maintainer, the newer versions *should* support proxies, but I see nothing in the [KPL configuration](https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java#L38) to enable it. Have you maybe tried just ensuring `http_proxy`+`https_proxy` env vars are available to the Logstash process? *possibly* KPL just passes that env down to the child daemon, which *possibly* just knows how to support that.

At any rate, I won't be able to do much for you here, other than recommend you seek clarification via awslabs/amazon-kinesis-producer#13
